### PR TITLE
Sl/dependent machines

### PR DESCRIPTION
**Pull request by slwu89**
@slibkind I'm adding a simplest possible example of the RM ODE model with an `InstantaneousContinuousMachine`; the composed dynamical system should be the exact same as the existing ODE model there.  The `oapply` is running into some problems when composing however, if you have a minute can you help me take a look? The composition pattern is ok so it must be an error in how I'm setting up the `InstantaneousContinuousMachine`.

The dyn sys should be:
EIR = m*a*Z
\kappa = c*X

\dot{Z} = a*\kappa*(e^{-gn} - Z) - gZ

\dot{X} = b*EIR*(1-X) - rX

### CODE REVIEW

**Comment by slwu89** [comment]
`oapply` works for me after changing the `induced_dynamics` and `induced_readout` methods to be less parametrically constrained, that is, `where {T,I, M<:AbstractMachine{T,I}}` to `where {M<:AbstractMachine}` in both those methods. Still encounter an error when running the ODE solver though!

**Comment by slwu89** [comment]
Update, trying out the example again after merging the latest (today) updates to the `sl/dependent_machines` branch. Error when calling `solve`:

```
ERROR: type Float64 has no field c
Stacktrace:
  [1] getproperty
    @ ./Base.jl:42 [inlined]
  [2] (::var"#5#6")(u::Vector{Float64}, x::LArray{Real, 1, Vector{Real}, (:a, :b, :c, :g, :n, :r, :m)}, p::Float64, t::Int64)
    @ Main ./REPL[15]:4
  [3] readout(m::AlgebraicDynamics.DWDDynam.Machine{Float64, AlgebraicDynamics.DWDDynam.InstantaneousDirectedInterface{Float64}, AlgebraicDynamics.DWDDynam.ContinuousDirectedSystem{Float64}}, u::Vector{Float64}, x::LArray{Real, 1, Vector{Real}, (:a, :b, :c, :g, :n, :r, :m)}, p::Float64, t::Int64) (repeats 2 times)
    @ AlgebraicDynamics.DWDDynam ~/Desktop/git/AlgebraicDynamics.jl/src/dwd_dynam.jl:261
  [4] (::AlgebraicDynamics.DWDDynam.var"#102#103"{Vector{Vector{Float64}}, LArray{Real, 1, Vector{Real}, (:a, :b, :c, :g, :n, :r, :m)}, Float64})(::Tuple{Int64, AlgebraicDynamics.DWDDynam.Machine{Float64, AlgebraicDynamics.DWDDynam.InstantaneousDirectedInterface{Float64}, AlgebraicDynamics.DWDDynam.ContinuousDirectedSystem{Float64}}})
    @ AlgebraicDynamics.DWDDynam ~/Desktop/git/AlgebraicDynamics.jl/src/dwd_dynam.jl:590
```

So the issue is here in dwd_dynam: https://github.com/AlgebraicJulia/AlgebraicDynamics.jl/blob/13d5935a231c278059bfba172e243cc96c2affa1/src/dwd_dynam.jl#L590-L592 which calls https://github.com/AlgebraicJulia/AlgebraicDynamics.jl/blob/13d5935a231c278059bfba172e243cc96c2affa1/src/dwd_dynam.jl#L261-L262

Somehow the wrong args are getting passed to the readout function, such that the time is getting sent into the spot where parameters should be passed.

**Comment by slibkind** [comment]
I think the problem comes from the fact that you are composing and `InstantaneousContinuousMachine` with two `ContinuousMachine`. A good addition to PR #99 would be to explicitly enable this. 

In the meantime a quick solution would be to write the mosquito and host models as instantaneous machines with trivial input/output dependency.  For example, instead of 
```
mosquito_model = ContinuousMachine{Float64}(1, 1, 1, dZdt, (u,p,t) -> u)
```

try

```
mosquito_model = InstantaneousContinuousMachine{Float64}(1, 1 ,1, dZdt, (u,x,p,t) -> u, [])
```

Another good addition to PR #99 would be to have a method which turns `ContinuousMachines` into `InstantaneousContinuousMachines`.

**Comment by slibkind** [comment]
Lastest commit on PR #99 adds a constructor for `InstantaneousMachine` from an ordinary machine. Now you should be able to write the above as: 

```
mosquito_model = ContinuousMachine{Float64}(1, 1, 1, dZdt, (u,p,t) -> u)
instantaneous_mosquito_model = InstantaneousContinuousMachine{Float64}(mosquito_model)
```

**Pull request merged**
